[package]
name = "hmacgen"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.44", features = ["derive", "env"] }
hex = "0.4.3"
hmac = "0.12.1"
rpassword = "7.4.0"
sha2 = "0.10.9"
